/// Flutter icons SignInIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SignInIcons
///      fonts:
///       - asset: fonts/SignInIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SignInIcons {
  SignInIcons._();

  static const _kFontFam = 'SignInIcons';
  static const String? _kFontPkg = null;

  static const IconData hive =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
